### PR TITLE
Begin refactoring

### PR DESCRIPTION
**Pull request by dperny**
This PR is for the beginning of a refactoring of isReactionaryBot. This pull request consists of two commits.

The first simple changes from tabs to 4 spaces. Tabs hurt my soul. If the changeover from tabs to spaces isn't to your liking, reject the PR and I'll do a new one without that change.

The second commit changes extractUsername to use a regex to find the user. The regex should be more robust and should handle /u/isreactionarybot username anywhere on the page (if you were to run it with this whole text as input, it should return "username". It's been roughly tested and should work, but might be broken in production. Caveat emptor.

### CODE REVIEW

**Comment by Wyboth** [comment]
I can deal with tabs to spaces, but I have a question about the regex. One reason I made the bot only search for '/u/isReactionaryBot' at the beginning of a line is to avoid replying to a comment that wasn't intended as a summon, like "I like /u/isReactionaryBot a lot!" The bot might think that was a summon, and investigate the user 'a'. In the current code, /u/isReactionaryBot has to be at the beginning of a line, and it must be followed by one space and one word. It ignores the line if there are two or more words after /u/isReactionaryBot's username, to avoid investigating when it shouldn't. My question is, does the current code do this, or something like it to make sure it does not reply to an unintended summon? If it does, I will go ahead and merge.

**Comment by dperny** [comment]
no, i hadn't thought of it like that. in its current iteration, it would detect any reference to /u/isReactionaryBot in any text and return the word following it.

I'll rework it in the morning to specifically find the summon on its own line.

**Comment by Wyboth** [comment]
Neat, thanks.

**Comment by dperny** [comment]
OK, this _should_ work. The only thing I changed is the regex itself; all the logic surround it is the same. I don't know how you test the robot, but it should probably be tested on your end too to make sure it still works as intended.

If you want to check the correctness of the regex, I use pythex.org; just copy and paste it in.

**Pull request merged**
